/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodosIndexRouteImport } from './routes/todos/index'
import { Route as GridIndexRouteImport } from './routes/grid/index'
import { Route as TodosCreateRouteImport } from './routes/todos/create'
import { Route as TodosTodoIdEditRouteImport } from './routes/todos/$todoId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosIndexRoute = TodosIndexRouteImport.update({
  id: '/todos/',
  path: '/todos/',
  getParentRoute: () => rootRouteImport,
} as any)
const GridIndexRoute = GridIndexRouteImport.update({
  id: '/grid/',
  path: '/grid/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosCreateRoute = TodosCreateRouteImport.update({
  id: '/todos/create',
  path: '/todos/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosTodoIdEditRoute = TodosTodoIdEditRouteImport.update({
  id: '/todos/$todoId/edit',
  path: '/todos/$todoId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/todos/create': typeof TodosCreateRoute
  '/grid': typeof GridIndexRoute
  '/todos': typeof TodosIndexRoute
  '/todos/$todoId/edit': typeof TodosTodoIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/todos/create': typeof TodosCreateRoute
  '/grid': typeof GridIndexRoute
  '/todos': typeof TodosIndexRoute
  '/todos/$todoId/edit': typeof TodosTodoIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/todos/create': typeof TodosCreateRoute
  '/grid/': typeof GridIndexRoute
  '/todos/': typeof TodosIndexRoute
  '/todos/$todoId/edit': typeof TodosTodoIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/todos/create' | '/grid' | '/todos' | '/todos/$todoId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/todos/create' | '/grid' | '/todos' | '/todos/$todoId/edit'
  id:
    | '__root__'
    | '/'
    | '/todos/create'
    | '/grid/'
    | '/todos/'
    | '/todos/$todoId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TodosCreateRoute: typeof TodosCreateRoute
  GridIndexRoute: typeof GridIndexRoute
  TodosIndexRoute: typeof TodosIndexRoute
  TodosTodoIdEditRoute: typeof TodosTodoIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/': {
      id: '/todos/'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid/': {
      id: '/grid/'
      path: '/grid'
      fullPath: '/grid'
      preLoaderRoute: typeof GridIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/create': {
      id: '/todos/create'
      path: '/todos/create'
      fullPath: '/todos/create'
      preLoaderRoute: typeof TodosCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/$todoId/edit': {
      id: '/todos/$todoId/edit'
      path: '/todos/$todoId/edit'
      fullPath: '/todos/$todoId/edit'
      preLoaderRoute: typeof TodosTodoIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TodosCreateRoute: TodosCreateRoute,
  GridIndexRoute: GridIndexRoute,
  TodosIndexRoute: TodosIndexRoute,
  TodosTodoIdEditRoute: TodosTodoIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
